[tool.poetry]
name = "big-eater"
version = "0.1.0"
description = ""
authors = ["Nathan Ndombasi <natrosity@Nathans-MacBook-Pro.local>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
